### ISSUE TITLE
The rant category header collides with rant once scrolled

### ISSUE THREAD

**Issue by asgs** [dr010001111/devrant-pwa#2]
![Screenshot_20201011-031648.png](https://user-images.githubusercontent.com/833190/95665732-a48ed980-0b70-11eb-8178-0c5a84748f58.png)

The categories shown at the top should probably move up once the scrolling begins. Otherwise, it gets in the way

**Comment by dr010001111** [comment]
@asgs Fixed on https://next.devrant.app/
